name: Update LeetCode Activity

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:        # Allows manual trigger from GitHub Actions

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Create .env File
        run: |
          echo "LEETCODE_USERNAME=${{ secrets.LEETCODE_USERNAME }}" >> .env

      - name: Configure Git identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Run Script
        run: python main.py

      - name: Push Changes to GitHub
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git add solved_problems.json
          git commit -m "Auto-update solved problems [$(date)]" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
