name: Update LeetCode Activity
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allows push with GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run updater (auto-commit & push inside script)
        env:
          LEETCODE_USERNAME: ${{ vars.LEETCODE_USERNAME }}
          # If you keep these, they’re optional:
          GIT_USERNAME: ${{ vars.GIT_USERNAME }}
          GIT_REPO: ${{ vars.GIT_REPO }}
          # For push/auth fallback (checkout already handles it, but passing is fine):
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python main.py